sonar.projectKey=aif369-web
sonar.projectName=AIF369 Web
sonar.sources=backend,assets,courses,dashboard,payment,verify
sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.log
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
