-- WhatsApp CRM agent: append-only bronze events and analytics-ready views.
-- Raw phone numbers are intentionally not stored; contact_hash is SHA-256.
--
-- Replace these placeholders before running:
--   __PROJECT_ID__ -> GCP project, for example aif369-backend
--   __DATASET_ID__ -> environment dataset, for example aif369_analytics_dev

CREATE TABLE IF NOT EXISTS `__PROJECT_ID__.__DATASET_ID__.whatsapp_crm_contacts` (
  event_id STRING NOT NULL,
  contact_hash STRING NOT NULL,
  display_name STRING,
  channel STRING NOT NULL,
  funnel_stage STRING,
  intent STRING,
  event_at TIMESTAMP NOT NULL,
  environment STRING
)
PARTITION BY DATE(event_at)
CLUSTER BY contact_hash, funnel_stage, intent
OPTIONS(description="Bronze CRM touchpoints generated by the WhatsApp sales agent");

CREATE OR REPLACE VIEW `__PROJECT_ID__.__DATASET_ID__.whatsapp_crm_contacts_silver` AS
SELECT
  contact_hash,
  ANY_VALUE(display_name HAVING MAX event_at) AS display_name,
  MIN(event_at) AS first_contact_at,
  MAX(event_at) AS last_contact_at,
  COUNT(*) AS touchpoints,
  ANY_VALUE(funnel_stage HAVING MAX event_at) AS current_funnel_stage,
  ANY_VALUE(intent HAVING MAX event_at) AS latest_intent
FROM `__PROJECT_ID__.__DATASET_ID__.whatsapp_crm_contacts`
GROUP BY contact_hash;

CREATE OR REPLACE VIEW `__PROJECT_ID__.__DATASET_ID__.whatsapp_funnel_gold` AS
SELECT
  DATE(event_at, "America/Santiago") AS event_date,
  funnel_stage,
  intent,
  COUNT(*) AS touchpoints,
  COUNT(DISTINCT contact_hash) AS unique_contacts
FROM `__PROJECT_ID__.__DATASET_ID__.whatsapp_crm_contacts`
GROUP BY event_date, funnel_stage, intent;
